#ifndef ULMK_CONFIG_H
#define ULMK_CONFIG_H
#define ULMK_CONFIG_MAX_THREADS       8
#define ULMK_CONFIG_MAX_ENDPOINTS     8
#define ULMK_CONFIG_MAX_NOTIFS        8
#define ULMK_CONFIG_MAX_IRQ_BINDINGS  4
#define ULMK_CONFIG_DEBUG_PRINTK      0
#define ULMK_CONFIG_SYSCALL_WCET     0
#define ULMK_CONFIG_ENABLE_SMP       0
#endif

