#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Single source of truth for the ulmk generated configuration headers.

Every build path (the CMake target build and the integration-test Makefiles)
invokes this script so the generated headers are always identical — no drift.

It emits two headers under <outdir>/ulmk/:

  config.h    Kernel sizing/policy actually consumed by kernel/*.c.
              This is the ONLY config header the kernel includes.

  platform.h  (optional, --board-config) SoC/board constants for the arch
              layer.  A normalized snapshot of boards/<soc>/board_config.h;
              the seam a future DTS pipeline will fill in.

Kernel policy lives here as the canonical default set; callers may override an
individual value with --set NAME=VALUE (e.g. the CMake cache exposes these to
the user via -DULMK_CONFIG_*).
"""

import argparse
import os
import sys

# Canonical kernel policy — the single place default sizing/policy is defined.
# Only symbols actually read by the real (non-UL_UNIT_TEST) kernel belong here.
KERNEL_DEFAULTS = {
    "ULMK_CONFIG_MAX_IRQ_BINDINGS": 16,   # irq.c static binding table
    "ULMK_CONFIG_DEBUG_PRINTK":     1,    # ulmk_printk.c (0 = no-op)
    "ULMK_CONFIG_SYSCALL_WCET":     0,    # kernel cycle slot around syscalls
    "ULMK_CONFIG_ENABLE_SMP":       0,    # 1 = multi-CPU sched (needs NUM_CPU>1)
    "ULMK_CONFIG_TICK_HZ":          1000, # kernel timing-wheel tick rate
}

# Inclusive range checks for numeric policy symbols.
KERNEL_RANGES = {
    "ULMK_CONFIG_MAX_IRQ_BINDINGS": (1, 256),
    "ULMK_CONFIG_SYSCALL_WCET":     (0, 1),
    "ULMK_CONFIG_ENABLE_SMP":       (0, 1),
    "ULMK_CONFIG_TICK_HZ":          (1, 10000),
}


def parse_overrides(pairs):
    out = {}
    for p in pairs:
        if "=" not in p:
            sys.exit("gen_config: --set expects NAME=VALUE, got %r" % p)
        name, value = p.split("=", 1)
        out[name.strip()] = value.strip()
    return out


def build_config(overrides):
    cfg = dict(KERNEL_DEFAULTS)
    for name, value in overrides.items():
        if name not in cfg:
            sys.exit("gen_config: unknown config symbol %r" % name)
        cfg[name] = int(value, 0)
    for name, (lo, hi) in KERNEL_RANGES.items():
        if not (lo <= cfg[name] <= hi):
            sys.exit("gen_config: %s=%d out of range [%d, %d]"
                     % (name, cfg[name], lo, hi))
    return cfg


def write_if_changed(path, text):
    if os.path.exists(path):
        with open(path, "r") as f:
            if f.read() == text:
                return
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(text)


def render_config(cfg):
    width = max(len(n) for n in cfg) + 1
    lines = [
        "/* Auto-generated by tools/gen_config.py — DO NOT EDIT.",
        " * Kernel sizing/policy.  Edit defaults in tools/gen_config.py or",
        " * override via -DULMK_CONFIG_* (CMake).",
        " */",
        "",
        "#ifndef ULMK_CONFIG_H",
        "#define ULMK_CONFIG_H",
        "",
    ]
    for name in cfg:
        lines.append("#define %-*s %d" % (width, name, cfg[name]))
    lines += ["", "#endif /* ULMK_CONFIG_H */", ""]
    return "\n".join(lines)


def render_platform(board_config_path):
    with open(board_config_path, "r") as f:
        body = f.read()
    banner = (
        "/* Auto-generated by tools/gen_config.py — DO NOT EDIT.\n"
        " * Snapshot of %s\n"
        " * (the arch layer includes this; a future DTS pipeline replaces it).\n"
        " */\n\n" % os.path.relpath(board_config_path)
    )
    return banner + body


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out-dir", required=True,
                    help="output root; headers land in <out-dir>/ulmk/")
    ap.add_argument("--set", action="append", default=[], metavar="NAME=VALUE",
                    help="override a kernel policy symbol")
    ap.add_argument("--board-config", default=None,
                    help="board_config.h to snapshot into ulmk/platform.h")
    args = ap.parse_args()

    cfg = build_config(parse_overrides(args.set))
    ulmk_dir = os.path.join(args.out_dir, "ulmk")
    write_if_changed(os.path.join(ulmk_dir, "config.h"), render_config(cfg))

    if args.board_config:
        if not os.path.exists(args.board_config):
            sys.exit("gen_config: board config not found: %s"
                     % args.board_config)
        write_if_changed(os.path.join(ulmk_dir, "platform.h"),
                         render_platform(args.board_config))


if __name__ == "__main__":
    main()
